CREATE TABLE IF NOT EXISTS connected
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IP_ADDRESS VARCHAR(128) NOT NULL,
    CONNECTED INT NOT NULL,
    LEASE_TIME INT NOT NULL
);

INSERT INTO connected (IP_ADDRESS)
SELECT 'ANI Received'
WHERE NOT EXISTS (SELECT 1 FROM EVENTTYPE WHERE EventTypeName = 'ANI Received');