CREATE TABLE IF NOT EXISTS connected
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    IP_ADDRESS VARCHAR(128) NOT NULL,
    CONNECTED INT NOT NULL,
    CONNECTED_IP VARCHAR(128) NOT NULL,
    LEASE_TIME INT NOT NULL
);